force-app/main/default/objects/Comment_On_Reader__c/Comment_On_Reader__c.object-meta.xml
<CustomObject>
    <label>Comment On Reader</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Comment On Reader Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments On Reader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment_On_Reader__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment_On_Reader__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Comments_On_Reader</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/services/CommentOnReaderService.cls
public inherited sharing class CommentOnReaderService {
    public static Comment_On_Reader__c insertCommentOnReader(Id userId, String text) {
        if (String.isBlank(userId) || String.isBlank(text)) {
            return null;
        }

        Comment_On_Reader__c commentOnReader = new Comment_On_Reader__c(
            User__c = userId,
            Time__c = Datetime.now(),
            Text__c = text
        );

        SecurityUtils.saveInsert(commentOnReader);

        return commentOnReader;
    }
}