force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
                <default>true</default>
                <label>created</label>
            </value>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>Status_Comment__c</fullName>
    <label>Status Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/controllers/ReservationController.cls
public with sharing class ReservationController {
    @AuraEnabled(Cacheable = true)
    public static List<Reservation__c> getReservationDatesByBookId(Id bookId) {
        return ReservationSelector.selector.getReservationDatesByBookId(bookId);
    }

    @AuraEnabled
    public static Reservation__c insertReservation(String jsonString) {
        return ReservationService.insertReservation(jsonString);
    }

    @AuraEnabled
    public static Reservation__c updateReservation(String jsonString) {
        return ReservationService.updateReservation(jsonString);
    }

    @AuraEnabled
    public static Reservation__c upsertReservation(String jsonString) {
        Id reservationId = ReservationService.upsertReservation(jsonString).Id;
        return ReservationSelector.selector.getByIds(new List<Id>{ reservationId })[0];
    }

    @AuraEnabled
    public static Reservation__c updateReservationStatus(Id reservationId, String status) {
        return ReservationService.updateReservationStatus(reservationId, status);
    }

    @AuraEnabled
    public static Reservation__c finishReservationByOwner(Id reservationId, Map<String, String> comments) {
        List<Reservation__c> reservationList = ReservationSelector.selector.getByIds(new List<Id>{ reservationId });

        if (reservationList.size() != 1 ) {
            return null;
        }

        Reservation__c reservation = reservationList[0];

        if (comments.containsKey('ReservationComment') && String.isNotBlank(comments.get('ReservationComment'))) {
            reservation.Status_Comment__c = comments.get('ReservationComment');
        }

        if (comments.containsKey('ReaderComment') && String.isNotBlank(comments.get('ReaderComment'))) {
            CommentOnReaderController.insertCommentOnReader(reservation.CreatedById, comments.get('ReaderComment'));
        }

        if (reservation.Status__c == ReservationConstants.STATUS_FINISHED_BY_READER) {
            reservation.Status__c = ReservationConstants.STATUS_FINISHED;
        } else {
            reservation.Status__c = ReservationConstants.STATUS_FINISHED_BY_OWNER;
        }

        return ReservationService.updateReservation(reservation);
    }

    @AuraEnabled
    public static Reservation__c finishReservationByReader(Id reservationId, Map<String, String> comments) {
        List<Reservation__c> reservationList = ReservationSelector.selector.getByIds(new List<Id>{ reservationId });

        if (reservationList.size() != 1 ) {
            return null;
        }

        Reservation__c reservation = reservationList[0];

        if (comments.containsKey('BookComment') && String.isNotBlank(comments.get('BookComment'))) {
            CommentOnBookController.insertCommentOnBook(reservation.Book__c, comments.get('BookComment'));
        }

        if (comments.containsKey('OwnerComment') && String.isNotBlank(comments.get('OwnerComment'))) {
            CommentOnOwnerController.insertCommentOnOwner(reservation.Book__r.OwnerId, comments.get('OwnerComment'));
        }

        if (reservation.Status__c == ReservationConstants.STATUS_FINISHED_BY_OWNER) {
            reservation.Status__c = ReservationConstants.STATUS_FINISHED;
        } else {
            reservation.Status__c = ReservationConstants.STATUS_FINISHED_BY_READER;
        }

        return ReservationService.updateReservation(reservation);
    }
}