force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <label>Actual End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Reservations</relationshipLabel>
    <relationshipName>Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
                <default>true</default>
                <label>created</label>
            </value>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reservation__c/fields/Status_Comment__c.field-meta.xml
<CustomField>
    <fullName>Status_Comment__c</fullName>
    <label>Status Comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/selectors/ReservationSelector.cls
public inherited sharing class ReservationSelector {
    public static ReservationSelector selector = new ReservationSelector();

    public List<Reservation__c> getReservationDatesByBookId(Id bookId) {
        return [
            SELECT
                Actual_End_Date__c,
                End_Date__c,
                Start_Date__c
            FROM Reservation__c
            WHERE
                Book__c = :bookId
                AND Actual_End_Date__c = NULL
                AND End_Date__c > TODAY
                AND Status__c IN :ReservationConstants.ACTIVE_RESERVATION_STATUSES
            WITH SECURITY_ENFORCED
            ORDER BY Start_Date__c
        ];
    }

    public List<Reservation__c> getByIds(List<Id> reservationIds) {
        return [
            SELECT
                Actual_End_Date__c,
                Book__c,
                Book__r.OwnerId,
                CreatedById,
                End_Date__c,
                Start_Date__c,
                Status__c,
                Status_Comment__c
            FROM Reservation__c
            WHERE Id IN :reservationIds
            WITH SECURITY_ENFORCED
        ];
    }

    public List<Reservation__c> getByBookIds(List<Id> bookIds) {
        return [
            SELECT
                Actual_End_Date__c,
                Book__c,
                Book__r.OwnerId,
                CreatedById,
                End_Date__c,
                Start_Date__c,
                Status__c,
                Status_Comment__c
            FROM Reservation__c
            WHERE Book__c IN :bookIds
            WITH SECURITY_ENFORCED
        ];
    }
}