force-app/main/default/objects/Reservation__c/Reservation__c.object-meta.xml
<CustomObject>
    <label>Reservation</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reservation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>created</fullName>
                <default>true</default>
                <label>created</label>
            </value>
            <value>
                <fullName>confirmed</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
            <value>
                <fullName>in progress</fullName>
            </value>
            <value>
                <fullName>success</fullName>
            </value>
            <value>
                <fullName>fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/ReservationService.cls
public inherited sharing class ReservationService {
    public static Reservation__c insertReservation(String jsonString) {
        Reservation__c reservation = (Reservation__c) JSON.deserialize(jsonString, Reservation__c.class);

        SecurityUtils.saveInsert(reservation);

        return reservation;
    }

    public static Reservation__c updateReservation(String jsonString) {
        Reservation__c reservation = (Reservation__c) JSON.deserialize(jsonString, Reservation__c.class);

        SecurityUtils.saveUpdate(reservation);

        return reservation;
    }

    public static Reservation__c updateReservation(Reservation__c reservation) {
        SecurityUtils.saveUpdate(reservation);

        return reservation;
    }

    public static Reservation__c upsertReservation(String jsonString) {
        Reservation__c reservation = (Reservation__c) JSON.deserialize(jsonString, Reservation__c.class);

        SecurityUtils.saveUpsert(reservation);

        return reservation;
    }

    public static Reservation__c updateReservationStatus(Id reservationId, String status) {
        Reservation__c reservation = new Reservation__c(
            Id = reservationId,
            Status__c = status
        );

        SecurityUtils.saveUpdate(reservation);

        return reservation;
    }
}