force-app/main/default/objects/Comment_On_Book__c/Comment_On_Book__c.object-meta.xml
<CustomObject>
    <label>Comment On Book</label>
    <nameField>
        <displayFormat>CB-{00000000}</displayFormat>
        <label>Comment On Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments On Book</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment_On_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Comments On Book</relationshipLabel>
    <relationshipName>Comments_On_Book</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comment_On_Book__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment_On_Book__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/services/CommentOnBookService.cls
public inherited sharing class CommentOnBookService {
    public static Comment_On_Book__c insertCommentOnBook(Id bookId, String text) {
        if (String.isBlank(bookId) || String.isBlank(text)) {
            return null;
        }

        Comment_On_Book__c commentOnBook = new Comment_On_Book__c(
            Book__c = bookId,
            Time__c = Datetime.now(),
            Text__c = text
        );

        SecurityUtils.saveInsert(commentOnBook);

        return commentOnBook;
    }
}