force-app/main/default/objects/Comment_On_Book__c/Comment_On_Book__c.object-meta.xml
<CustomObject>
    <label>Comment On Book</label>
    <nameField>
        <displayFormat>CB-{00000000}</displayFormat>
        <label>Comment On Book Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments On Book</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment_On_Book__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Comments On Book</relationshipLabel>
    <relationshipName>Comments_On_Book</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comment_On_Book__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Comment_On_Book__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/selectors/CommentOnBookSelector.cls
public inherited sharing class CommentOnBookSelector {
    public static CommentOnBookSelector selector = new CommentOnBookSelector();

    public List<Comment_On_Book__c> getCommentsByBookId(Id bookId) {
        return [
            SELECT
                CreatedBy.Name,
                Text__c,
                Time__c
            FROM Comment_On_Book__c
            WHERE Book__c = :bookId
            WITH SECURITY_ENFORCED
        ];
    }
}