force-app/main/default/objects/Favourite__c/Favourite__c.object-meta.xml
<CustomObject>
    <label>Favourite</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Favourite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Favourites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Favourite__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Favourites</relationshipLabel>
    <relationshipName>Favourites</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/services/FavouriteService.cls
public inherited sharing class FavouriteService {
    public static Favourite__c addToFavourite(Id bookId) {
        if (String.isBlank(bookId)) {
            return null;
        }

        Favourite__c favourite = new Favourite__c(Book__c = bookId);
        SecurityUtils.saveInsert(favourite);

        return favourite;
    }

    public static void removeFromFavourite(Id favouriteId) {
        SecurityUtils.saveDelete(new Favourite__c(Id = favouriteId));
    }
}