force-app/main/default/objects/Wish_List__c/Wish_List__c.object-meta.xml
<CustomObject>
    <label>Wish List</label>
    <nameField>
        <displayFormat>WL-{00000000}</displayFormat>
        <label>Wish List Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wish Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Wish_List__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Book</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Wish Lists</relationshipLabel>
    <relationshipName>Wish_Lists</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/services/WishListService.cls
public inherited sharing class WishListService {
    public static Wish_List__c addToWishList(Id bookId) {
        if (String.isBlank(bookId)) {
            return null;
        }

        Wish_List__c wishList = new Wish_List__c(Book__c = bookId);
        SecurityUtils.saveInsert(wishList);

        return wishList;
    }

    public static void removeFromWishList(Id wishListId) {
        SecurityUtils.saveDelete(new Wish_List__c(Id = wishListId));
    }
}