force-app/main/default/objects/Comment_On_Owner__c/Comment_On_Owner__c.object-meta.xml
<CustomObject>
    <label>Comment On Owner</label>
    <nameField>
        <displayFormat>CO-{00000000}</displayFormat>
        <label>Comment On Owner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments On Owner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment_On_Owner__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Comments_On_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/services/CommentOnOwnerService.cls
public inherited sharing class CommentOnOwnerService {
    public static Comment_On_Owner__c insertCommentOnOwner(Id userId, String text) {
        if (String.isBlank(userId) || String.isBlank(text)) {
            return null;
        }

        Comment_On_Owner__c commentOnOwner = new Comment_On_Owner__c(
            User__c = userId,
            Time__c = Datetime.now(),
            Text__c = text
        );

        SecurityUtils.saveInsert(commentOnOwner);

        return commentOnOwner;
    }
}